# Generated by Django 5.0.4 on 2024-04-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ip_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
