# Generated by Django 5.0.4 on 2024-04-24 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer_app', '0004_alter_timer_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ip_address',
        ),
    ]
